openapi: 3.1.0
info:
  title: REST API
  description: uma api rest usando go, e openAPI, feita em goLang
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: Listar users
      responses:
        '200':
          description: lista de users que serao introduzidos no banco de dados
      
  
    post:
      summary: Criar um user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: user criado com sucesso
        '400':
          description: Requisição inválida
